name: Build Archi Plugin

on:
  workflow_dispatch:       # Enables manual trigger
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout Archi
        uses: actions/checkout@v4
        with:
          repository: archimatetool/archi
          path: archi

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build Archi
        working-directory: archi
        run: mvn -B -q clean -DskipTests verify

      - name: Build plugin with Tycho
        run: |
          ARCHI_REPO=$(realpath  /home/runner/work/archi-scripting-plugin/archi-scripting-plugin/archi)
          find  /home/runner/work/archi-scripting-plugin/archi-scripting-plugin/archi -type d
          echo "Arch repo: $ARCHI_REPO"
          mvn -B -q clean verify -Darchi.p2.repo=$ARCHI_REPO

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: archi-plugin
          path: com.archimatetool.script/target/*.jar
